### ISSUE TITLE
Select your team suggestions

### ISSUE THREAD

**Issue by chefgs** [runitmisra/squad_health#1]
Keep the project selection combo box next to `Select your team` and  Make `box size` fixed and smaller size.

**Comment by runitmisra** [comment]
Hello @chefgs,
Does this look ok?
![image](https://user-images.githubusercontent.com/32189847/157632629-223dcbe4-d7f7-4749-8473-a413e968db00.png)

**Comment by runitmisra** [comment]
I have also added a '-' option which will be default so that people don't make mistakes

**Comment by chefgs** [comment]
@runitmisra  If possible to move the selection box closer to the text `Select your team`. Otherwise looks fine!

**Comment by runitmisra** [comment]
Brought the box a bit closer to the text:
![image](https://user-images.githubusercontent.com/32189847/157667385-00c08a3a-a02b-4ab9-8786-d0f8bde2240e.png)

I'll be closing this issue now.
Thanks @chefgs for the feedback.
